In [1]:
import numpy as np


In [2]:
a=np.array( [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ] )

In [3]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a[0][1:5:1]

array([2, 3, 4])

In [5]:
a[[0],[0]]

array([1])

In [6]:
a[[2],[0]]

array([9])

In [7]:
a.shape

(3, 4)

In [8]:
a[2,1:3]


array([10, 11])

In [9]:
a[2,1:6:1]

array([10, 11, 12])

In [10]:
a[[0,2],[1,0]]

array([2, 9])

In [11]:
a[1:,2:]#n[row:,collumn:]

array([[ 7,  8],
       [11, 12]])

In [12]:
a[1,:2]

array([5, 6])

# arange

In [13]:
list (range(5,10))

[5, 6, 7, 8, 9]

In [14]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [15]:
np.arange(2.5,22.1)

array([ 2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5,
       13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5])

# reshape

In [16]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
np.sqrt(4)

2.0

In [18]:
a.max()

12

In [19]:
a.mean()

6.5

In [20]:
a.argmax()

11

In [21]:
a*3

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [22]:
a.argmax()

11

In [23]:
a+3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# random

In [24]:
np.random.rand(2,2)

array([[0.51643345, 0.75649925],
       [0.86676948, 0.51441863]])

In [25]:
np.random.rand(2)

array([0.73448721, 0.02059738])

In [26]:
np.random .randint(9,88,5)

array([20, 16, 28, 81, 81])

In [27]:
np.random.randint(9,88,8).reshape(2,4)

array([[14, 23, 80, 77],
       [10, 82, 77, 16]])

In [28]:
a.sum()

78

In [29]:
a.sum(axis=1)#collumn wise sum

array([10, 26, 42])

# 3D

In [30]:
d=np.array ([ [[4,40],[5,50],[6,60] ], [ [7,70],[8,80],[9,90] ], [ [5,50],[4,40],[6,60] ] ])

In [31]:
d.shape

(3, 3, 2)

# nan -not a number 

In [32]:
x=np.array([12,56,np.nan,66,100,np.nan])

In [33]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [34]:
x.dtype

dtype('float64')

# pandas

In [35]:
import pandas as pd

In [47]:
import numpy as np

In [48]:
n=np.array([1,2,3,4,5,6])

In [49]:
n

array([1, 2, 3, 4, 5, 6])

In [50]:
z =pd.Series(n)

In [51]:
z

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [52]:
type(z)

pandas.core.series.Series

In [55]:
m= pd.Series([1,2,[11,234,45],[32,12,12],3,45,6])

In [56]:
m

0                1
1                2
2    [11, 234, 45]
3     [32, 12, 12]
4                3
5               45
6                6
dtype: object

In [58]:
m[0]

1

In [59]:
m[2]

[11, 234, 45]

In [60]:
z

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32

In [62]:
z['m':]

TypeError: cannot do slice indexing on RangeIndex with these indexers [m] of type str